# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Modify_JPG_Metadata.ui'
#
# Created by: PyQt5 UI code generator 5.8
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 340)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(20, 100, 360, 81))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setLineWidth(2)
        self.frame_2.setObjectName("frame_2")
        self.TextCopyright = QtWidgets.QLineEdit(self.frame_2)
        self.TextCopyright.setGeometry(QtCore.QRect(10, 40, 340, 22))
        self.TextCopyright.setObjectName("TextCopyright")
        self.LabelCopyright = QtWidgets.QLabel(self.frame_2)
        self.LabelCopyright.setGeometry(QtCore.QRect(10, 10, 91, 20))
        self.LabelCopyright.setObjectName("LabelCopyright")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 290, 361, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ButtonSelectImages = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.ButtonSelectImages.setObjectName("ButtonSelectImages")
        self.horizontalLayout.addWidget(self.ButtonSelectImages)
        self.ButtonApply = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.ButtonApply.setObjectName("ButtonApply")
        self.horizontalLayout.addWidget(self.ButtonApply)
        self.ButtonClose = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.ButtonClose.setObjectName("ButtonClose")
        self.horizontalLayout.addWidget(self.ButtonClose)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 10, 360, 80))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setLineWidth(2)
        self.frame.setObjectName("frame")
        self.ComboClassification = QtWidgets.QComboBox(self.frame)
        self.ComboClassification.setGeometry(QtCore.QRect(10, 40, 181, 22))
        self.ComboClassification.setObjectName("ComboClassification")
        self.ComboClassification.addItem("")
        self.LabelCopyright_3 = QtWidgets.QLabel(self.frame)
        self.LabelCopyright_3.setGeometry(QtCore.QRect(10, 10, 91, 20))
        self.LabelCopyright_3.setObjectName("LabelCopyright_3")
        self.LabelSelected = QtWidgets.QLabel(self.frame)
        self.LabelSelected.setEnabled(True)
        self.LabelSelected.setGeometry(QtCore.QRect(190, 10, 150, 20))
        self.LabelSelected.setAutoFillBackground(False)
        self.LabelSelected.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LabelSelected.setObjectName("LabelSelected")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(20, 190, 360, 91))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_3.setLineWidth(2)
        self.frame_3.setObjectName("frame_3")
        self.TextTags = QtWidgets.QLineEdit(self.frame_3)
        self.TextTags.setGeometry(QtCore.QRect(10, 40, 340, 44))
        self.TextTags.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.TextTags.setObjectName("TextTags")
        self.LabelCopyright_2 = QtWidgets.QLabel(self.frame_3)
        self.LabelCopyright_2.setGeometry(QtCore.QRect(10, 10, 161, 20))
        self.LabelCopyright_2.setObjectName("LabelCopyright_2")
        self.CheckBoxRemove = QtWidgets.QCheckBox(self.frame_3)
        self.CheckBoxRemove.setGeometry(QtCore.QRect(200, 10, 151, 20))
        self.CheckBoxRemove.setChecked(False)
        self.CheckBoxRemove.setObjectName("CheckBoxRemove")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.ComboClassification, self.TextCopyright)
        MainWindow.setTabOrder(self.TextCopyright, self.TextTags)
        MainWindow.setTabOrder(self.TextTags, self.CheckBoxRemove)
        MainWindow.setTabOrder(self.CheckBoxRemove, self.ButtonSelectImages)
        MainWindow.setTabOrder(self.ButtonSelectImages, self.ButtonApply)
        MainWindow.setTabOrder(self.ButtonApply, self.ButtonClose)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Modify Metadata"))
        self.LabelCopyright.setText(_translate("MainWindow", "Copyright Text"))
        self.ButtonSelectImages.setText(_translate("MainWindow", "Select Images"))
        self.ButtonApply.setText(_translate("MainWindow", "Apply"))
        self.ButtonClose.setText(_translate("MainWindow", "Close"))
        self.ComboClassification.setItemText(0, _translate("MainWindow", "Unclassified"))
        self.LabelCopyright_3.setText(_translate("MainWindow", "Classification"))
        self.LabelSelected.setText(_translate("MainWindow", "0 pictures selected"))
        self.TextTags.setPlaceholderText(_translate("MainWindow", "Tags must be semicolon deliminated"))
        self.LabelCopyright_2.setText(_translate("MainWindow", "Tags"))
        self.CheckBoxRemove.setText(_translate("MainWindow", "Remove Exisint Tags"))

